# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-24 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ideaticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idea_title', models.CharField(max_length=100)),
                ('idea_no', models.IntegerField()),
                ('idea_text', models.CharField(max_length=500)),
                ('idea_link', models.CharField(max_length=100)),
            ],
        ),
    ]
